name: Python CI
 
on: [push, pull_request]
 
jobs:
  lint:
    name: Lint code with Pylint, Pyflakes, and AutoPEP8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pylint pyflakes autopep8 radon

      - name: Set up GitHub token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Test with pytest
        id: pytest
        run: |
          pip install pytest pytest-cov
          pytest test_merge_file.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=

      - name: Check AutoPep8 Formatting
        run: |
         autopep8 --diff --aggressive --aggressive hw2_debugging.py
        continue-on-error: true

      - name: Update Autopep8 Badge
        run: |
          diff=$(git diff)
          formatted="true"
          if [[ ! -z "$diff" ]]; then
            formatted="false"
          fi
          color="green"
          if [[ "$formatted" == "false" ]]; then
            color="red"
          fi
          echo '{
            "schemaVersion": 1,
            "label": "autopep8",
            "message": "formatted",
            "color": "'$color'"
          }' > badges/autopep8.json


      # Pylint check and badge update
      - name: Run Pylint
        run: |
          pylint hw2_debugging.py
        continue-on-error: true
  
      - name: Generate Pylint Report
        id: pylint
        run: |
          pylint_score=$(pylint --exit-zero hw2_debugging.py --output-format=json | jq '[.[].score | select(. != null)] | if length > 0 then add / length else 0 end')
          color="red"
          if (( $(echo "$pylint_score >= 8" | bc -l) )); then
            color="green"
          elif (( $(echo "$pylint_score >= 5" | bc -l) )); then
            color="yellow"
          fi
          echo '{
            "schemaVersion": 1,
            "label": "pylint",
            "message": "'$pylint_score'/10",
            "color": "'$color'"
          }' > badges/pylint.json


      # Pyflakes type checking and badge update
      - name: Run Pyflakes
        run: |
          pyflakes hw2_debugging.py || true
        continue-on-error: true
      
      - name: Update Pyflakes Badge
        run: |
          pyflakes_errors=$(pyflakes hw2_debugging.py | wc -l)
          color="green"
          if [[ "$pyflakes_errors" -gt 0 ]]; then
            color="red"
          fi
          echo '{
            "schemaVersion": 1,
            "label": "pyflakes",
            "message": "'$pyflakes_errors' errors",
            "color": "'$color'"
          }' > badges/pyflakes.json


      # Commit updated badges back to the repo
      - name: Commit badge updates
        run: |
          git config --local user.email "pdinesh.ms7@gmail.com"
          git config --local user.name "dinesh-pasupuleti"
    
          git add badges/*.json
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update badges"
            git push origin HEAD:main
          else
            echo "No changes to badges, skipping commit."
          fi
