name: Python CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint code with Pylint, Pyflakes, and AutoPEP8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pylint pyflakes autopep8

      - name: Run Pylint and save output
        run: |
          pylint . > pylint-report.txt || true
        continue-on-error: true

      - name: Run Pyflakes and save output
        run: pyflakes . > pyflakes-report.txt || true

      - name: Run AutoPEP8 and apply formatting
        run: autopep8 --in-place --aggressive --aggressive $(git ls-files '*.py')
      
      - name: Upload Pylint report
        uses: actions/upload-artifact@v2
        with:
          name: pylint-report
          path: pylint-report.txt

      - name: Upload Pyflakes report
        uses: actions/upload-artifact@v2
        with:
          name: pyflakes-report
          path: pyflakes-report.txt
