name: Python CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint code with Pylint, Pyflakes, and AutoPEP8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pylint pyflakes autopep8 radon

      - name: Test with pytest
        id: pytest
        run: |
          pip install pytest pytest-cov
          pytest test_merge_file.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=

      - name: Check AutoPep8 Formatting
        run: |
          autopep8 --diff --aggressive --aggressive hw2_debugging.py
        continue-on-error: true
  
      - name: Update Autopep8 Badge
        run: |
          diff=$(git diff)
          formatted="true"
          if [[ ! -z "$diff" ]]; then
            formatted="false"
          fi
          color="green"
          if [[ "$formatted" == "false" ]]; then
            color="red"
          fi
          echo '{
            "schemaVersion": 1,
            "label": "autopep8",
            "message": "formatted",
            "color": "'$color'"
          }' > badges/autopep8.json
