name: Python CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint code with Pylint, Pyflakes, and AutoPEP8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pylint pyflakes autopep8 radon

      - name: Test with pytest
        id: pytest
        run: |
          pip install pytest pytest-cov
          pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      
      - name: Run Pylint and save output
        run: |
          pylint . > pylint-report.txt || true
        continue-on-error: true

      - name: Run Pyflakes and save output
        run: pyflakes . > pyflakes-report.txt || true

      - name: Run AutoPEP8 and apply formatting
        run: autopep8 --in-place --aggressive --aggressive $(git ls-files '*.py')

      - name: Run Radon
        run: |
          radon cc hw2_debugging.py -a
      
      - name: Upload Pylint report
        uses: actions/upload-artifact@v3
        with:
          name: pylint-report
          path: pylint-report.txt

      - name: Upload Pyflakes report
        uses: actions/upload-artifact@v3
        with:
          name: pyflakes-report
          path: pyflakes-report.txt
